[package]
name = "vrind_scroll"
version = "0.1.0"
authors = ["nick <Nick Aerts>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.3.19"
rusttype = "0.8.1"
nphysics2d = "0.12.3"
nalgebra = "0.18.1"